const ADDTOCART = "ADD_TO_CART";

const REMOVEFROMCART = "REMOVE_FROM_CART";

const INCREASEQUANTITY = "INCREASE_QUANTITY";
const DECREASEQUANTITY = "DECREASE_QUANTITY";

export { ADDTOCART, REMOVEFROMCART, INCREASEQUANTITY, DECREASEQUANTITY };
